"""Tray/menu-bar app: polls Jira/GitHub on a timer, shows native notifications,
and opens the relevant URL when a notification is clicked.

The GUI toolkit is abstracted behind a platform backend (see
``platform_backend``): macOS uses rumps (AppKit), Windows uses pystray +
winotify. This module contains only toolkit-neutral logic — timers,
notifications, menu structure, polling — and drives the active backend through
its interface.

@author SteveZou
"""
import json
import os
import sys
import threading
import time
from datetime import datetime, timezone

import config as cfg_mod
import deps as deps_mod
import poll as poll_mod
import updater as updater_mod
from platform_backend import get_backend
from platform_backend.base import MenuItem

# Selectable tray themes. Each has a colored lightning-bolt PNG icon in
# assets/menubar/<name>.png (generated by scripts/generate_icon.py).
THEMES = ["Orange", "Green", "Purple", "Rainbow", "Yellow"]
DEFAULT_THEME = "Orange"


def _assets_dir():
    """Locate the assets dir both from source and inside a PyInstaller bundle."""
    if getattr(sys, "frozen", False):
        base = os.path.dirname(sys.executable)  # Contents/MacOS
        candidates = [
            os.path.join(base, "assets", "menubar"),
            os.path.join(base, "_internal", "assets", "menubar"),
            # PyInstaller .app puts datas under Contents/Resources
            os.path.join(base, "..", "Resources", "assets", "menubar"),
            os.path.join(getattr(sys, "_MEIPASS", base), "assets", "menubar"),
        ]
        for c in candidates:
            if os.path.isdir(c):
                return os.path.normpath(c)
        return candidates[0]
    return os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "assets", "menubar",
    )


def _theme_icon(theme: str):
    path = os.path.join(_assets_dir(), f"{theme}.png")
    return path if os.path.exists(path) else None


def _theme_checking_icon(theme: str):
    """Themed 'checking' (busy) spinner icon, or None if not bundled."""
    path = os.path.join(_assets_dir(), f"{theme}-checking.png")
    return path if os.path.exists(path) else None


def _save_config(cfg: dict) -> None:
    try:
        cfg_mod.config_path().write_text(
            json.dumps(cfg, indent=2, ensure_ascii=False), encoding="utf-8"
        )
    except OSError as e:
        _log(f"ERROR writing config: {e}")


def _log(msg: str) -> None:
    line = f"{datetime.now(timezone.utc).isoformat()} {msg}"
    try:
        with cfg_mod.LOG_FILE.open("a", encoding="utf-8") as f:
            f.write(line + "\n")
    except OSError:
        pass


def _load_state() -> dict:
    if cfg_mod.STATE_FILE.exists():
        try:
            return json.loads(cfg_mod.STATE_FILE.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            pass
    return {"seen": {}}


def _save_state(state: dict, cfg: dict = None) -> None:
    # The seen-TTL must outlive the maximum lookback window; otherwise an event
    # still inside the window whose seen-entry expired would be re-notified.
    # Event-level fingerprints are stable (unlike the old issue+updated ones),
    # so this edge case is real. Keep at least 7 days, plus a 3-day margin over
    # the configured max window.
    max_window_min = (cfg or {}).get("poll", {}).get("max_window_minutes", 10080)
    ttl = max(7 * 86400, max_window_min * 60 + 3 * 86400)
    cutoff = time.time() - ttl
    state["seen"] = {k: v for k, v in state.get("seen", {}).items() if v >= cutoff}
    try:
        cfg_mod.STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")
    except OSError as e:
        _log(f"ERROR writing state: {e}")


class NotifierApp:
    # Old theme names -> current ones (config migration).
    THEME_ALIASES = {"Bell": "Yellow"}

    def __init__(self, backend=None):
        self.backend = backend if backend is not None else get_backend()
        self.cfg = cfg_mod.ensure_config()
        theme = self.cfg.get("theme", DEFAULT_THEME)
        theme = self.THEME_ALIASES.get(theme, theme)
        if theme not in THEMES:
            theme = DEFAULT_THEME
        self.cfg["theme"] = theme
        icon = _theme_icon(theme)
        # Colored (non-template) icon so themes show their color in the tray.
        self.backend.setup(name="DevNotifier", icon=icon)
        self.icon = icon
        self.title = None
        if not icon:  # fallback to an emoji if the PNG is missing
            self.title = "\U0001f514"
            self.backend.set_title(self.title)
        self.state = _load_state()
        self.recent = []  # list of {id, label, url} entries for the menu
        self._recent_counter = 0
        self._polling = False  # guard against overlapping polls (slow network)
        self._checking = False  # True while a manual check is in flight (UI hint)
        self._base_title = None  # tray title without the "checking" indicator
        # Defer dependency checks off the startup path: check_dependencies()
        # shells out to `gh` (network calls, up to 15s each) which would block
        # the tray icon from appearing. Start with a placeholder status,
        # draw the menu immediately, then run the real check in the background.
        self.dep_status = {
            "gh": {"installed": False, "authed": False, "login": "", "detail": ""},
            "jira": {"enabled": False, "configured": False, "detail": ""},
            "pagerduty": {"enabled": False, "configured": False, "detail": ""},
            "github_ok": False,
            "jira_ok": False,
            "pagerduty_ok": False,
            "ok": False,
            "problems": [],
            "pending": True,  # first real check hasn't run yet
        }
        # Update-check state, rendered in the menu and refreshed off-thread.
        self.update_info = {
            "available": False,
            "current": updater_mod.current_version(),
            "latest": "",
            "html_url": updater_mod.RELEASES_PAGE,
            "dmg_url": None,
            "dmg_name": None,
            "installer_url": None,
            "installer_name": None,
            "sha256_url": None,
            "from_source": not updater_mod.is_frozen(),
            "error": None,
        }
        self._downloading = False  # guard against overlapping downloads
        self.menu = []  # neutral MenuItem list (also read by tests)
        self._build_menu()
        # Run the first dependency check + startup warning shortly after the
        # event loop starts, so the icon shows up instantly.
        self._startup_timer = self.backend.add_timer(self._initial_check, 0.5)
        interval = self.cfg.get("poll", {}).get("interval_seconds", 300)
        self.timer = self.backend.add_timer(self.on_tick, interval)
        # Update checks: one shortly after launch (one-shot), then on a slow
        # recurring timer. Both run the network call on a worker thread so the
        # tray never blocks.
        self._update_startup_timer = self.backend.add_timer(
            self._initial_update_check, 3.0
        )
        hours = self.cfg.get("update", {}).get("check_interval_hours", 24)
        self.update_timer = self.backend.add_timer(
            self._on_update_tick, max(1, int(hours)) * 3600
        )

    def run(self):
        self.backend.run()

    def _initial_check(self, sender):
        """Kick off the first dependency check in the background (one-shot)."""
        sender.stop()

        def worker():
            status = deps_mod.check_dependencies(self.cfg)

            def apply(_):
                self.dep_status = status
                self._build_menu()
                self._warn_if_unmet()

            self._run_on_main(apply)

        threading.Thread(target=worker, daemon=True).start()

    # -- update checks ------------------------------------------------------
    def _initial_update_check(self, sender):
        """One-shot update check shortly after launch (off the startup path)."""
        sender.stop()
        self._run_update_check(notify=True)

    def _on_update_tick(self, _):
        """Recurring background update check (every check_interval_hours)."""
        self._run_update_check(notify=True)

    def _check_updates_now(self, _):
        """Menu 'Check for updates': check and always give visible feedback."""
        self._run_update_check(notify=True, manual=True)

    def _run_update_check(self, notify=False, manual=False):
        """Check GitHub Releases on a worker thread; apply results on main.

        Never blocks the tray: all network I/O happens in the worker; only
        menu/notification updates are handed back to the main thread.
        """
        def worker():
            info = updater_mod.check_for_update(self.cfg)

            def apply(_):
                self.update_info = info
                self._build_menu()
                if manual and not info.get("available"):
                    if info.get("from_source"):
                        sub, msg = "Running from source", \
                            "Update checks apply to installed builds only."
                    elif info.get("error"):
                        sub, msg = "Couldn't check", \
                            "Check your network and try again."
                    else:
                        sub, msg = "Up to date", \
                            f"You're on the latest version ({info['current']})."
                    self._post_notification(
                        title="Dev Notifier — updates",
                        subtitle=sub, message=msg, data={}, sound=False,
                    )
                elif notify and info.get("available"):
                    self._post_notification(
                        title="Dev Notifier — update available",
                        subtitle=f"Version {info['latest']} is available",
                        message="Open the menu to download and install.",
                        data={"url": info.get("html_url", "")},
                        sound=False,
                    )

            self._run_on_main(apply)

        threading.Thread(target=worker, daemon=True).start()

    def _download_update(self, _):
        """Download + verify the installer, then open it (off the main thread)."""
        if self._downloading:
            self._post_notification(
                title="Dev Notifier", subtitle="Already downloading…",
                message="The update download is already in progress.",
                data={}, sound=False,
            )
            return
        self._downloading = True
        info = dict(self.update_info)
        self._post_notification(
            title="Dev Notifier", subtitle="Downloading update…",
            message=f"Fetching version {info.get('latest', '')}.",
            data={}, sound=False,
        )

        def worker():
            try:
                result = updater_mod.download_and_open(info, log=_log)
            finally:
                self._downloading = False

            def apply(_):
                if result.get("ok"):
                    self._post_notification(
                        title="Dev Notifier — update ready",
                        subtitle="Installer opened",
                        message="Follow the installer to replace the old "
                                "version, then relaunch.",
                        data={}, sound=True,
                    )
                else:
                    self._post_notification(
                        title="Dev Notifier — update failed",
                        subtitle="Could not download",
                        message=result.get("error", "Try the Releases page.")[:200],
                        data={"url": info.get("html_url", "")}, sound=False,
                    )

            self._run_on_main(apply)

        threading.Thread(target=worker, daemon=True).start()

    def _open_release_page(self, _):
        url = self.update_info.get("html_url") or updater_mod.RELEASES_PAGE
        self.backend.open_url(url)

    def _skip_this_version(self, _):
        ver = self.update_info.get("latest", "")
        if ver:
            self.cfg.setdefault("update", {})["skipped_version"] = ver
            _save_config(self.cfg)
            self.update_info["available"] = False
            self._build_menu()
            _log(f"update {ver} skipped")

    def _run_on_main(self, fn):
        """Schedule ``fn`` to run once on the main thread.

        UI updates must happen on the platform's main thread; worker threads use
        this to hand results back safely. The active backend decides how (macOS:
        AppHelper.callAfter; Windows: inline).
        """
        self.backend.run_on_main(fn)

    def _enter_checking(self):
        """Show the themed 'checking' spinner icon + in-menu hint (main thread)."""
        self._checking = True
        theme = self.cfg.get("theme", DEFAULT_THEME)
        spinner = _theme_checking_icon(theme)
        if spinner:
            self.icon = spinner
            self.backend.set_icon(spinner)
        self._build_menu()

    def _exit_checking(self):
        """Restore the normal themed icon + menu after a check (main thread)."""
        self._checking = False
        theme = self.cfg.get("theme", DEFAULT_THEME)
        icon = _theme_icon(theme)
        if icon:
            self.icon = icon
            self.backend.set_icon(icon)
        self._build_menu()

    def _post_notification(self, **kwargs):
        """Post a native notification using the active theme's colored icon.

        The theme's PNG becomes the notification's identity image so
        notifications match the tray theme instead of a plain square.

        When the notification carries a URL, add an explicit "Open" action
        button. On macOS the click handler only fires for the notification body
        or an explicit action button; the system default button alone does not
        deliver the URL, so clicking it appears to do nothing.
        """
        if "icon" not in kwargs:
            theme = self.cfg.get("theme", DEFAULT_THEME)
            icon = _theme_icon(theme)
            if icon:
                kwargs["icon"] = icon
        if "action_button" not in kwargs and (kwargs.get("data") or {}).get("url"):
            kwargs["action_button"] = "Open"
        self.backend.notify(**kwargs)

    def _warn_if_unmet(self):
        """On startup, if nothing is usable, guide the user via a notification."""
        if not self.dep_status.get("ok"):
            msg = self.dep_status["problems"][0] if self.dep_status["problems"] \
                else "Open config file to set up Jira/GitHub."
            try:
                self._post_notification(
                    title="Dev Notifier — setup needed",
                    subtitle="No working source yet",
                    message=msg,
                    data={},
                    sound=False,
                )
            except Exception:  # noqa: BLE001
                pass

    # -- menu ---------------------------------------------------------------
    def _build_menu(self):
        if self._checking:
            # Immediate, in-menu feedback that a manual check is running.
            items = [MenuItem("Checking…", callback=None)]
        else:
            items = [MenuItem("Check now", callback=self.check_now)]
        # status line
        items.append(self._status_menuitem())
        items.append(MenuItem.sep())
        if self.recent:
            items.append(MenuItem("Recent:", callback=None))
            for entry in self.recent[:10]:
                items.append(self._recent_submenu(entry))
            items.append(MenuItem.sep())
            items.append(MenuItem("Clear all recent", callback=self._clear_recent))
        else:
            items.append(MenuItem("(no recent items)", callback=None))
        items.append(MenuItem.sep())
        # Update entry: a prominent submenu when a newer version exists,
        # otherwise a plain manual "Check for updates" action.
        items.append(self._update_menuitem())
        items.append(MenuItem.sep())
        items.append(self._theme_submenu())
        # start-at-login toggle
        login_item = MenuItem("Start at login", callback=self._toggle_login_item)
        login_item.state = 1 if self.backend.login_item_enabled() else 0
        items.append(login_item)
        items.append(MenuItem("Check dependencies", callback=self._recheck_deps))
        items.append(MenuItem("Open config file", callback=self._open_config))
        items.append(MenuItem("Quit", callback=self._quit))
        self.menu = items
        self.backend.set_menu(items)

    def _quit(self, _=None):
        self.backend.quit()

    def _status_menuitem(self):
        """Status ▸ submenu with one short line per source (Jira / GitHub)."""
        s = self.dep_status
        if s.get("pending"):
            # First background check hasn't finished yet.
            parent = MenuItem("Status", callback=self._recheck_deps)
            parent.add(MenuItem("Checking…", callback=None))
            parent.add(MenuItem.sep())
            parent.add(MenuItem("Re-check now", callback=self._recheck_deps))
            return parent
        if s["jira_ok"]:
            jira_line = "Jira: ✓ Ready"
        elif s["jira"]["enabled"]:
            jira_line = "Jira: ⚠ Needs setup"
        else:
            jira_line = "Jira: Off"
        if s["github_ok"]:
            github_line = "GitHub: ✓ Ready"
        elif self.cfg.get("github", {}).get("enabled"):
            github_line = "GitHub: ⚠ Needs login"
        else:
            github_line = "GitHub: Off"
        if s.get("pagerduty_ok"):
            pd_line = "PagerDuty: ✓ Ready"
        elif self.cfg.get("pagerduty", {}).get("enabled"):
            pd_line = "PagerDuty: ⚠ Needs token"
        else:
            pd_line = "PagerDuty: Off"

        parent = MenuItem("Status", callback=self._recheck_deps)
        parent.add(MenuItem(jira_line, callback=None))
        parent.add(MenuItem(github_line, callback=None))
        parent.add(MenuItem(pd_line, callback=None))
        parent.add(MenuItem.sep())
        parent.add(MenuItem("Re-check now", callback=self._recheck_deps))
        return parent

    def _update_menuitem(self):
        """Update ▸ submenu when a newer release exists; else a plain action."""
        info = self.update_info
        if info.get("available"):
            parent = MenuItem(f"Update available: {info['latest']} ▸")
            parent.add(MenuItem("Download & Install",
                                callback=self._download_update))
            parent.add(MenuItem("Release notes",
                                callback=self._open_release_page))
            parent.add(MenuItem.sep())
            parent.add(MenuItem("Skip this version",
                                callback=self._skip_this_version))
            return parent
        return MenuItem("Check for updates", callback=self._check_updates_now)

    def _recheck_deps(self, _):
        # Run the (network-bound) check on a worker thread so the tray does
        # not freeze; apply the result on the main thread.
        def worker():
            status = deps_mod.check_dependencies(self.cfg)

            def apply(_):
                self.dep_status = status
                self._build_menu()
                if status["problems"]:
                    self._post_notification(
                        title="Dev Notifier — dependency check",
                        subtitle="Issues found",
                        message="; ".join(status["problems"])[:200],
                        data={}, sound=False,
                    )
                else:
                    self._post_notification(
                        title="Dev Notifier — dependency check",
                        subtitle="All good",
                        message="Jira / GitHub are ready.",
                        data={}, sound=False,
                    )

            self._run_on_main(apply)

        threading.Thread(target=worker, daemon=True).start()

    def _toggle_login_item(self, sender):
        if self.backend.login_item_enabled():
            ok = self.backend.disable_login_item()
            _log(f"login item disabled ok={ok}")
        else:
            ok = self.backend.enable_login_item()
            _log(f"login item enabled ok={ok}")
        self._build_menu()

    def _theme_submenu(self):
        """Theme ▸ submenu; the active theme is checkmarked and shows its icon."""
        current = self.cfg.get("theme", DEFAULT_THEME)
        parent = MenuItem("Theme")
        for name in THEMES:
            item = MenuItem(name, callback=self._set_theme)
            item.theme_name = name
            item.state = 1 if name == current else 0
            icon = _theme_icon(name)
            if icon:
                try:
                    item.set_icon(icon, dimensions=(16, 16), template=False)
                except Exception:  # noqa: BLE001
                    pass
            parent.add(item)
        return parent

    def _set_theme(self, sender):
        name = getattr(sender, "theme_name", DEFAULT_THEME)
        self.cfg["theme"] = name
        _save_config(self.cfg)
        # If a check is in flight, keep showing the (themed) spinner variant.
        icon = _theme_checking_icon(name) if self._checking else None
        if not icon:
            icon = _theme_icon(name)
        if icon:
            self.icon = icon
            self.backend.set_icon(icon)
        else:
            self.title = "\U0001f514"
            self.backend.set_title(self.title)
        self._build_menu()
        _log(f"theme changed to {name}")

    def _recent_submenu(self, entry: dict):
        """Each recent item is a submenu: title -> Open / Remove."""
        parent = MenuItem(entry["label"])
        open_item = MenuItem("Open", callback=self._open_recent)
        open_item.entry_id = entry["id"]
        remove_item = MenuItem("Remove", callback=self._remove_recent)
        remove_item.entry_id = entry["id"]
        parent.add(open_item)
        parent.add(remove_item)
        return parent

    def _find_recent(self, entry_id):
        for e in self.recent:
            if e["id"] == entry_id:
                return e
        return None

    def _open_recent(self, sender):
        entry = self._find_recent(getattr(sender, "entry_id", None))
        if entry and entry.get("url"):
            self.backend.open_url(entry["url"])

    def _remove_recent(self, sender):
        entry_id = getattr(sender, "entry_id", None)
        self.recent = [e for e in self.recent if e["id"] != entry_id]
        self._build_menu()

    def _clear_recent(self, _):
        self.recent = []
        self._build_menu()

    def _open_config(self, _):
        self.backend.open_url(str(cfg_mod.config_path()))

    # -- polling ------------------------------------------------------------
    def check_now(self, _):
        # Manual pull: give IMMEDIATE visible feedback (themed spinner icon +
        # "Checking…" menu item) so the click registers instantly, even though
        # the network work runs in the background and results arrive later.
        if not self._polling:
            self._enter_checking()
        self.on_tick(None, manual=True)

    def on_tick(self, _, manual=False):
        """Timer/manual entry point. Runs the network work off the main thread
        so the tray never freezes; all UI/notification work is handed back
        to the main thread when the poll finishes."""
        if self._polling:
            # A previous poll is still running (slow network). Skip overlapping
            # runs; on a manual trigger, tell the user it's already working.
            if manual:
                self._post_notification(
                    title="Dev Notifier",
                    subtitle="Already checking…",
                    message="A check is already in progress.",
                    data={}, sound=False,
                )
            return
        self._polling = True

        def worker():
            try:
                self._poll_once(manual)
            finally:
                self._polling = False

        threading.Thread(target=worker, daemon=True).start()

    def _poll_once(self, manual):
        """Do the network-bound poll on a worker thread; apply results on main."""
        cfg = cfg_mod.ensure_config()
        dep_status = deps_mod.check_dependencies(cfg)
        if not dep_status.get("ok"):
            _log("WARN: no usable source; " + "; ".join(dep_status["problems"]))

            def apply_unusable(_):
                self.cfg = cfg
                self.dep_status = dep_status
                if manual and self._checking:
                    self._exit_checking()  # restores icon + rebuilds menu
                else:
                    self._build_menu()
                    self._post_notification(
                        title="Dev Notifier",
                        subtitle="Nothing to check",
                        message=(dep_status["problems"][0]
                                 if dep_status["problems"]
                                 else "Configure Jira/GitHub first."),
                        data={}, sound=False,
                    )

            self._run_on_main(apply_unusable)
            return

        _log("=== poll start ===")
        # Window spans from the previous poll to now (capped by
        # max_window_minutes). Snapshot the start time *before* fetching so any
        # update that lands during this poll is caught by the next one.
        since_ts = self.state.get("last_poll")
        poll_started = time.time()
        try:
            phases = poll_mod.collect_all(cfg, log=_log, since_ts=since_ts)
        except Exception as e:  # noqa: BLE001
            _log(f"ERROR collect_all: {e}")
            # Bind the message here: ``e`` is scoped to this ``except`` block and
            # is cleared once it exits, but ``apply_error`` may run later (on the
            # main thread, deferred), so it must close over a plain string.
            err_msg = f"Could not fetch updates: {e}"[:200]

            def apply_error(_):
                if manual and self._checking:
                    self._exit_checking()
                if manual:
                    self._post_notification(
                        title="Dev Notifier",
                        subtitle="Check failed",
                        message=err_msg,
                        data={}, sound=False,
                    )

            self._run_on_main(apply_error)
            return

        # Apply results (notifications, state, menu) on the main thread.
        def apply_results(_):
            self.cfg = cfg
            self.dep_status = dep_status
            seen = self.state.setdefault("seen", {})
            new_count = 0
            for _phase, items in phases:
                for it in items:
                    fp = it["fp"]
                    if fp in seen:
                        continue
                    if it.get("ci_only") and it.get("ci_rollup") == "pass":
                        seen[fp] = time.time()
                        continue
                    url = it.get("url", "")
                    # Notify only; the URL opens when the user clicks the
                    # notification (or a Recent entry). No auto-open.
                    self._notify(it)
                    self._recent_counter += 1
                    self.recent.insert(0, {
                        "id": self._recent_counter,
                        "label": f"{it['subtitle']} — {it['message']}"[:80],
                        "url": url,
                    })
                    seen[fp] = time.time()
                    new_count += 1
            self.recent = self.recent[:10]
            # Advance the poll cursor only after a successful fetch so the next
            # window starts where this one began (no gap, no missed updates).
            self.state["last_poll"] = poll_started
            _save_state(self.state, cfg)
            if manual and self._checking:
                self._exit_checking()  # restores icon + rebuilds menu
            else:
                self._build_menu()
            _log(f"=== poll done: {new_count} new ===")
            if manual and new_count == 0:
                self._post_notification(
                    title="Dev Notifier",
                    subtitle="Checked — no new items",
                    message="You're all caught up.",
                    data={}, sound=False,
                )

        self._run_on_main(apply_results)

    def _notify(self, it: dict):
        url = it.get("url", "")
        _log(f"NOTIFY [{it['title']}] {it['subtitle']} | {it['message']} -> {url}")
        # Notify only; clicking the notification opens the URL.
        try:
            self._post_notification(
                title=it["title"],
                subtitle=it["subtitle"],
                message=it["message"],
                data={"url": url},
                sound=True,
            )
        except Exception as e:  # noqa: BLE001
            _log(f"ERROR notification: {e}")


def main():
    NotifierApp().run()


if __name__ == "__main__":
    main()
