"""Menu-bar app: polls Jira/GitHub on a timer, shows native macOS
notifications, and opens the relevant URL when a notification is clicked.

@author SteveZou
"""
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone

import rumps

import config as cfg_mod
import deps as deps_mod
import poll as poll_mod

# Selectable menu-bar themes. Each has a colored lightning-bolt PNG icon in
# assets/menubar/<name>.png (generated by scripts/generate_icon.py).
THEMES = ["Orange", "Green", "Purple", "Rainbow", "Bell"]
DEFAULT_THEME = "Orange"


def _assets_dir():
    """Locate the assets dir both from source and inside a PyInstaller bundle."""
    if getattr(sys, "frozen", False):
        base = os.path.dirname(sys.executable)  # Contents/MacOS
        candidates = [
            os.path.join(base, "assets", "menubar"),
            os.path.join(base, "_internal", "assets", "menubar"),
            # PyInstaller .app puts datas under Contents/Resources
            os.path.join(base, "..", "Resources", "assets", "menubar"),
            os.path.join(getattr(sys, "_MEIPASS", base), "assets", "menubar"),
        ]
        for c in candidates:
            if os.path.isdir(c):
                return os.path.normpath(c)
        return candidates[0]
    return os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "assets", "menubar",
    )


def _theme_icon(theme: str):
    path = os.path.join(_assets_dir(), f"{theme}.png")
    return path if os.path.exists(path) else None


def _save_config(cfg: dict) -> None:
    try:
        cfg_mod.config_path().write_text(
            json.dumps(cfg, indent=2, ensure_ascii=False), encoding="utf-8"
        )
    except OSError as e:
        _log(f"ERROR writing config: {e}")


def _log(msg: str) -> None:
    line = f"{datetime.now(timezone.utc).isoformat()} {msg}"
    try:
        with cfg_mod.LOG_FILE.open("a", encoding="utf-8") as f:
            f.write(line + "\n")
    except OSError:
        pass


def _load_state() -> dict:
    if cfg_mod.STATE_FILE.exists():
        try:
            return json.loads(cfg_mod.STATE_FILE.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            pass
    return {"seen": {}}


def _save_state(state: dict) -> None:
    cutoff = time.time() - 7 * 86400
    state["seen"] = {k: v for k, v in state.get("seen", {}).items() if v >= cutoff}
    try:
        cfg_mod.STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")
    except OSError as e:
        _log(f"ERROR writing state: {e}")


@rumps.notifications
def _on_click(info):
    """Fired when the user clicks a delivered notification."""
    url = (info.data or {}).get("url")
    if url:
        subprocess.run(["open", url], check=False)


class NotifierApp(rumps.App):
    def __init__(self):
        self.cfg = cfg_mod.ensure_config()
        theme = self.cfg.get("theme", DEFAULT_THEME)
        icon = _theme_icon(theme)
        # Colored (non-template) icon so themes show their color in the menu bar.
        super().__init__(
            name="DevNotifier",
            icon=icon,
            template=False,
            quit_button=None,
        )
        if not icon:  # fallback to an emoji if the PNG is missing
            self.title = "\U0001f514"
        self.state = _load_state()
        self.recent = []  # list of {id, label, url} entries for the menu
        self._recent_counter = 0
        self.dep_status = deps_mod.check_dependencies(self.cfg)
        self._build_menu()
        self._warn_if_unmet()
        interval = self.cfg.get("poll", {}).get("interval_seconds", 300)
        self.timer = rumps.Timer(self.on_tick, interval)
        self.timer.start()

    def _warn_if_unmet(self):
        """On startup, if nothing is usable, guide the user via a notification."""
        if not self.dep_status.get("ok"):
            msg = self.dep_status["problems"][0] if self.dep_status["problems"] \
                else "Open config file to set up Jira/GitHub."
            try:
                rumps.notification(
                    title="Dev Notifier — setup needed",
                    subtitle="No working source yet",
                    message=msg,
                    data={},
                    sound=False,
                )
            except Exception:  # noqa: BLE001
                pass

    # -- menu ---------------------------------------------------------------
    def _build_menu(self):
        self.menu.clear()
        items = [rumps.MenuItem("Check now", callback=self.check_now)]
        # status line
        items.append(self._status_menuitem())
        items.append(rumps.separator)
        if self.recent:
            items.append(rumps.MenuItem("Recent:", callback=None))
            for entry in self.recent[:10]:
                items.append(self._recent_submenu(entry))
            items.append(rumps.separator)
            items.append(rumps.MenuItem("Clear all recent", callback=self._clear_recent))
        else:
            items.append(rumps.MenuItem("(no recent items)", callback=None))
        items.append(rumps.separator)
        items.append(self._theme_submenu())
        # start-at-login toggle
        login_item = rumps.MenuItem("Start at login", callback=self._toggle_login_item)
        login_item.state = 1 if deps_mod.login_item_enabled() else 0
        items.append(login_item)
        items.append(rumps.MenuItem("Check dependencies", callback=self._recheck_deps))
        items.append(rumps.MenuItem("Open config file", callback=self._open_config))
        items.append(rumps.MenuItem("Quit", callback=rumps.quit_application))
        self.menu = items

    def _status_menuitem(self):
        s = self.dep_status
        parts = []
        parts.append("Jira ✓" if s["jira_ok"] else
                     ("Jira …" if s["jira"]["enabled"] else "Jira off"))
        parts.append("GitHub ✓" if s["github_ok"] else
                     ("GitHub …" if self.cfg.get("github", {}).get("enabled")
                      else "GitHub off"))
        label = "Status: " + "  ·  ".join(parts)
        item = rumps.MenuItem(label, callback=self._recheck_deps)
        return item

    def _recheck_deps(self, _):
        self.dep_status = deps_mod.check_dependencies(self.cfg)
        self._build_menu()
        s = self.dep_status
        if s["problems"]:
            rumps.notification(
                title="Dev Notifier — dependency check",
                subtitle="Issues found",
                message="; ".join(s["problems"])[:200],
                data={}, sound=False,
            )
        else:
            rumps.notification(
                title="Dev Notifier — dependency check",
                subtitle="All good",
                message="Jira / GitHub are ready.",
                data={}, sound=False,
            )

    def _toggle_login_item(self, sender):
        if deps_mod.login_item_enabled():
            ok = deps_mod.disable_login_item()
            _log(f"login item disabled ok={ok}")
        else:
            ok = deps_mod.enable_login_item()
            _log(f"login item enabled ok={ok}")
        self._build_menu()

    def _theme_submenu(self):
        """Theme ▸ submenu; the active theme is checkmarked and shows its icon."""
        current = self.cfg.get("theme", DEFAULT_THEME)
        parent = rumps.MenuItem("Theme")
        for name in THEMES:
            item = rumps.MenuItem(name, callback=self._set_theme)
            item.theme_name = name
            item.state = 1 if name == current else 0
            icon = _theme_icon(name)
            if icon:
                try:
                    item.set_icon(icon, dimensions=(16, 16), template=False)
                except Exception:  # noqa: BLE001
                    pass
            parent.add(item)
        return parent

    def _set_theme(self, sender):
        name = getattr(sender, "theme_name", DEFAULT_THEME)
        self.cfg["theme"] = name
        _save_config(self.cfg)
        icon = _theme_icon(name)
        if icon:
            self.icon = icon
        else:
            self.title = "\U0001f514"
        self._build_menu()
        _log(f"theme changed to {name}")

    def _recent_submenu(self, entry: dict):
        """Each recent item is a submenu: title -> Open / Remove."""
        parent = rumps.MenuItem(entry["label"])
        open_item = rumps.MenuItem("Open", callback=self._open_recent)
        open_item.entry_id = entry["id"]
        remove_item = rumps.MenuItem("Remove", callback=self._remove_recent)
        remove_item.entry_id = entry["id"]
        parent.add(open_item)
        parent.add(remove_item)
        return parent

    def _find_recent(self, entry_id):
        for e in self.recent:
            if e["id"] == entry_id:
                return e
        return None

    def _open_recent(self, sender):
        entry = self._find_recent(getattr(sender, "entry_id", None))
        if entry and entry.get("url"):
            subprocess.run(["open", entry["url"]], check=False)

    def _remove_recent(self, sender):
        entry_id = getattr(sender, "entry_id", None)
        self.recent = [e for e in self.recent if e["id"] != entry_id]
        self._build_menu()

    def _clear_recent(self, _):
        self.recent = []
        self._build_menu()

    def _open_config(self, _):
        subprocess.run(["open", str(cfg_mod.config_path())], check=False)

    # -- polling ------------------------------------------------------------
    def check_now(self, _):
        self.on_tick(None)

    def on_tick(self, _):
        self.cfg = cfg_mod.ensure_config()
        self.dep_status = deps_mod.check_dependencies(self.cfg)
        if not self.dep_status.get("ok"):
            _log("WARN: no usable source; " + "; ".join(self.dep_status["problems"]))
            self._build_menu()
            return
        seen = self.state.setdefault("seen", {})
        max_open = self.cfg.get("poll", {}).get("max_auto_open", 3)
        opened = 0
        new_count = 0
        _log("=== poll start ===")
        try:
            phases = poll_mod.collect_all(self.cfg, log=_log)
        except Exception as e:  # noqa: BLE001
            _log(f"ERROR collect_all: {e}")
            return
        for _phase, items in phases:
            for it in items:
                fp = it["fp"]
                if fp in seen:
                    continue
                if it.get("ci_only") and it.get("ci_rollup") == "pass":
                    seen[fp] = time.time()
                    continue
                url = it.get("url", "")
                self._notify(it, open_now=(bool(url) and opened < max_open))
                if url and opened < max_open:
                    opened += 1
                self._recent_counter += 1
                self.recent.insert(0, {
                    "id": self._recent_counter,
                    "label": f"{it['subtitle']} — {it['message']}"[:80],
                    "url": url,
                })
                seen[fp] = time.time()
                new_count += 1
        self.recent = self.recent[:10]
        _save_state(self.state)
        self._build_menu()
        _log(f"=== poll done: {new_count} new, {opened} opened ===")

    def _notify(self, it: dict, open_now: bool):
        url = it.get("url", "")
        _log(f"NOTIFY [{it['title']}] {it['subtitle']} | {it['message']} -> {url}")
        # Open immediately for the primary items; the notification click can
        # re-open any of them later.
        if open_now and url:
            subprocess.run(["open", url], check=False)
        try:
            rumps.notification(
                title=it["title"],
                subtitle=it["subtitle"],
                message=it["message"],
                data={"url": url},
                sound=True,
            )
        except Exception as e:  # noqa: BLE001
            _log(f"ERROR notification: {e}")


def main():
    NotifierApp().run()


if __name__ == "__main__":
    main()
